# 运行阶段
FROM ccr.ccs.tencentyun.com/itqm-private/alpine:3.22

# 设置 apk aliyun 源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

# 安装必要的运行时依赖
RUN apk add --no-cache ca-certificates tzdata

# 设置时区
ENV TZ=Asia/Shanghai

# 设置工作目录
WORKDIR /app

RUN mkdir -p /app/config

# 从构建阶段复制二进制文件
COPY backend/bin/market /app/market

# 运行应用
CMD ["/app/market"]